name: fluttemis_platform_ui_apps

ide:
  intellij:
    enabled: false

packages:
  - fluttemis_platform_ui_dependency_module
  - fluttemis_platform_ui_core
  - fluttemis_platform_ui_design_system
  - fluttemis_platform_ui_app

command:
  bootstrap:
    usePubspecOverrides: true
  version:
    updateGitTagRefs: true
    branch: main

scripts:
  test:flutter:
    run: melos exec flutter test --coverage
    description: Run test in all projects packages.
    select-package:
      flutter: true
      dir-exists: test

  analyze:
    exec: dart analyze .