name: fluttemis_platform_ui_apps

ide:
  intellij:
    enabled: false

packages:
  - fluttemis_platform_ui_dependency_module
  - fluttemis_platform_ui_core
  - fluttemis_platform_ui_design_system
  - fluttemis_platform_ui_locus
  - fluttemis_platform_ui_app

command:
  bootstrap:
    usePubspecOverrides: true
  version:
    updateGitTagRefs: true
    branch: main

scripts:

  test:flutter:
    run:  melos exec -c 4 --fail-fast -- "flutter test --coverage"
    description: Run Flutter test in all projects packages.
    select-package:
      flutter: true
      dir-exists: test

  analyze:
    exec: dart analyze .

  localization:flutter:
    exec: flutter gen-l10n
    description: Run gen-l10n to generate localizations files.
    select-package:
      flutter: true
      file-exists: lib/l10n/app_pt.arb

  enable:macos:build:
    exec: flutter config --enable-macos-desktop
    description: Enable macOS build
    select-package:
      flutter: true
      file-exists: lib/main.dart

  macos:build:
    exec: flutter build macos --release
    description: Run fluttemis build macos in release mode.
    select-package:
      flutter: true
      file-exists: lib/main.dart

  macos:create-dmg:
    run: | 
      /bin/sh ./scripts/create_mac_dmg.sh
    description: Create fluttemis macos dmg file
    select-package:
      flutter: true
      file-exists: lib/main.dart

  enable:windows:build:
    exec: flutter config --enable-windows-desktop
    description: Enable windows build
    select-package:
      flutter: true
      file-exists: lib/main.dart

  windows:build:
    exec: flutter build windows --release
    description: Run fluttemis build windows in release mode.
    select-package:
      flutter: true
      file-exists: lib/main.dart

  windows:create-msix:
    exec: flutter pub run msix:create
    description: Create windows msix file
    select-package:
      flutter: true
      file-exists: lib/main.dart

  enable:linux:build:
    exec: flutter config --enable-linux-desktop
    description: Enable linux build
    select-package:
      flutter: true
      file-exists: lib/main.dart

  linux:build:
    exec: flutter build linux --release
    description: Run fluttemis build linux in release mode.
    select-package:
      flutter: true
      file-exists: lib/main.dart
