name: fluttemis_platform_ui_design_system
description: Fluttemis project using platform ui design system app.
version: 1.1.0
homepage: none
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.3.6"

dependencies:
  flutter:
    sdk: flutter
  fluttemis_platform_ui_dependency_module:
    path: ../fluttemis_platform_ui_dependency_module
  fluttemis_platform_ui_core:
    path: ../fluttemis_platform_ui_core
  fluent_ui: 4.0.3
  macos_ui: 1.7.6
 
dev_dependencies:
  dart_code_metrics: ^5.0.1
  flutter_test:
    sdk: flutter
  lint: ^1.10.0