name: fluttemis_platform_ui_locus
description: Fluttemis project using platform ui locus app.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.3.6"

dependencies:
  flutter:
    sdk: flutter
  fluttemis_platform_ui_dependency_module:
    path: ../fluttemis_platform_ui_dependency_module
  fluttemis_platform_ui_core:
    path: ../fluttemis_platform_ui_core
  fluttemis_platform_ui_design_system:
    path: ../fluttemis_platform_ui_design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.0.1
  lint: ^1.10.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
