name: fluttemis_platform_ui_locus
description: Fluttemis project using platform ui locus app.
version: 1.1.0
homepage: none
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.3.6"

dependencies:
  flutter:
    sdk: flutter
  fluttemis_platform_ui_dependency_module:
    path: ../fluttemis_platform_ui_dependency_module
  fluttemis_platform_ui_core:
    path: ../fluttemis_platform_ui_core
  fluttemis_platform_ui_design_system:
    path: ../fluttemis_platform_ui_design_system

dev_dependencies:
  dart_code_metrics: ^4.19.2
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
  mocktail: ^0.3.0
  path: ^1.8.2
  value_listenable_test: ^0.0.1

flutter:
  uses-material-design: true