name: fluttemis_platform_ui_core
description: Fluttemis project using platform ui core app.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.3.6"

dependencies:
  flutter:
    sdk: flutter
  fluttemis_platform_ui_dependency_module:
    path: ../fluttemis_platform_ui_dependency_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.19.2
  lint: ^1.10.0