name: fluttemis_platform_ui_dependency_module
description: Fluttemis project using platform ui packages register app.
version: 1.1.0
homepage: none
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.3.6"
 
dependencies:
  dart_bio_package:
    git: 
      url: https://github.com/oberdancunha/dart-bio-package.git
      ref: 2.1.0
  collection: ^1.16.0
  equatable: ^2.0.5
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^5.0.3
  window_manager: ^0.2.7
  intl: ^0.17.0
  lottie: ^2.0.0
  touchable: ^1.0.2
  linked_scroll_controller: ^0.2.0
  selectable: ^0.2.9
  clipboard_watcher: ^0.1.3
  uuid: ^3.0.7
  fpdart: ^0.5.0
  kt_dart: ^1.1.0
  data_table_2: 2.3.10
  sealed_unions: ^3.0.3+1
  bitsdojo_window: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  generate: true