name: fluttemis_platform_ui_dependency_module
description: Fluttemis project using platform ui packages register app.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.3.6"
 
dependencies:
  dart_bio_package:
    git: 
      url: https://github.com/oberdancunha/dart-bio-package.git
      ref: 2.0.0
  collection: ^1.16.0
  equatable: ^2.0.5
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^5.0.3
  window_manager: ^0.2.7
  intl: ^0.17.0
  lottie: ^2.0.0
  data_table_2: ^2.3.10
  touchable: ^1.0.2
  linked_scroll_controller: ^0.2.0
  selectable: ^0.2.9
  clipboard_watcher: ^0.1.3
  uuid: ^3.0.7
  fpdart: ^0.5.0
  kt_dart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
