name: Fluttemis build release

env:
  flutter_version: "3.3.6"
  flutter_channel: "stable"
  flutter_architecture: x64
  melos_version: "2.9.0"
  fluttemis_app: "fluttemis_platform_ui_app"

on: push

jobs:
  build-and-release-macos:
    runs-on: macos-latest
    steps:
      - name: "Git checkout"
        uses: actions/checkout@v2
      - name: "Install flutter ${{env.flutter_version}} version"
        uses: subosito/flutter-action@v2
        with:
          channel: ${{env.flutter_channel}}
          architecture: ${{env.flutter_architecture}}
          flutter-version: ${{env.flutter_version}}
      - name: "Install Melos ${{env.melos_version}} tool"
        run: flutter pub global activate melos ${{env.melos_version}}
      - name: "Melos bootstrap"
        run: melos bootstrap --verbose
      - name: "Melos analyze"
        run: melos run analyze
      - name: "Flutter test"
        run: melos run test:flutter
      - name: Generate localizations files
        run: melos run localization:flutter
      - name: Enable macOS build
        run: melos run enable:macos:build
      - name: Build macOS release
        run: melos run macos:build
      - name: Zip macOS release
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          filename: Fluttemis-macos.zip
          directory: ${{env.fluttemis_app}}/build/macos/Build/Products/Release
      - name: Creating Github macOS release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: ${{env.fluttemis_app}}/build/macos/Build/Products/Release/Fluttemis-macos.zip