name: Fluttemis build release

env:
  flutter_version: "3.3.6"
  flutter_channel: "stable"
  flutter_architecture: x64
  melos_version: "2.9.0"
  fluttemis_app: "fluttemis_platform_ui_app"
  git_checkout_title: "Git checkout"
  install_melos_title: "Install Melos tool"
  melos_bootstrap_title: "Melos bootstrap"
  melos_analyze_title: "Melos analyze"
  flutter_test_title: "Flutter test"
  generate_localizations_files_title: "Generate localizations files"

on:
  push:
    tags:
      - "v*.*.*"
   
jobs:
  build-and-release-macos:
    runs-on: macos-latest
    steps:
      - name: ${{env.git_checkout_title}}
        uses: actions/checkout@v2

      - name: "Install flutter ${{env.flutter_version}} version"
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: ${{env.flutter_channel}}
          architecture: ${{env.flutter_architecture}}
          flutter-version: ${{env.flutter_version}}

      - name: Set Up XCode
        uses: devbotsxyz/xcode-select@v1.1.0

      - name: ${{env.install_melos_title}}
        run: flutter pub global activate melos ${{env.melos_version}}

      - name: ${{env.melos_bootstrap_title}}
        run: melos bootstrap --verbose

      - name: ${{env.melos_analyze_title}}
        run: melos run analyze

      - name: ${{env.flutter_test_title}}
        run: melos run test:flutter

      - name: ${{env.generate_localizations_files_title}}
        run: melos run localization:flutter

      - name: Enable macOS build
        run: melos run enable:macos:build

      - name: Build macOS release
        run: melos run macos:build

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create mac dmg
        run: melos run macos:create-dmg

      - name: Zip macOS release
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          filename: Fluttemis-macos.zip
          directory: ${{env.fluttemis_app}}/build/macos/Build/Products/Release

      - name: Creating Github DMG macOS release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: ${{env.fluttemis_app}}/build/macos/Build/Products/Release/Fluttemis.dmg
          
      - name: Creating Github ZIP macOS release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: ${{env.fluttemis_app}}/build/macos/Build/Products/Release/Fluttemis-macos.zip